#!/usr/bin/env python
#=========================================================================
# plot-transistor-trends
#=========================================================================
#
#  -h --help          Display this message
#
# Author : Shreesha Srinath
# Date   : March 18th, 2018
#
# data collected from Stanford CPUDB and this link:
# https://github.com/karlrupp/microprocessor-trend-data/blob/master/42yrs/transistors.dat

import argparse
import re
import math
import sys

import pandas as pd
pd.set_option('display.width', 1000)

import brg_plot

from matplotlib.pyplot import Text

#-------------------------------------------------------------------------
# main
#-------------------------------------------------------------------------

if __name__ == "__main__":
 
  # create plot options dict
  opts = brg_plot.PlotOptions()
  attribute_dict = \
  {
    'show'            : False,
    'plot_type'       : 'scatter',
    'figsize'         : (4.0, 4.0),
    'rotate_labels'   : False,
    'markersize'      : 10,
    'labels_fontsize' : 1,
    'legend_enabled'  : False,
  }
  for name, value in attribute_dict.iteritems():
    setattr( opts, name, value )

  # get data
  df = pd.read_csv('cpudb-clean.csv')
  df.loc[:,'transistors'] *= 1000000

  ylabel = 'transistors'
  yaxis = df.loc[:,ylabel].tolist()
  xaxis = df.loc[:,'year'].tolist()
  data = []
  for x,y in zip( xaxis, yaxis ):
    data.append( [x,y] )

  # new data
  # https://github.com/karlrupp/microprocessor-trend-data/blob/master/42yrs/transistors.dat
  new_data = [
  [2011,1170000000],
  [2011,2600000000],
  [2011,1200000000],
  [2012,2400000000],
  [2012,2300000000],
  [2012,2100000000],
  [2012,1200000000],
  [2013,5000000000],
  [2013,4300000000],
  [2014,4300000000],
  [2014,4200000000],
  [2014,2600000000],
  [2014,3800000000],
  [2014,5700000000],
  [2016,7200000000],
  [2016,8000000000],
  [2017,19200000000]
  ]

  for point in new_data:  
    x = point[0]
    y = point[1]
    data.append( [x,y] )

  opts.xrange            = [1970, 2018]
  opts.num_cols          = 1
  opts.num_rows          = 1 
  opts.data              = [data]
  opts.index             = 1
  opts.log_yaxis         = True
  opts.colors            = ['#8aae92'] 
  opts.ylabel            = 'Transistors per Chip' 
  opts.grid_enabled      = False
  
  brg_plot.add_plot( opts )

  ax = opts.fig.gca()

  ax.axvline( x=1985, zorder=1, linewidth=0.5, color='k')
  ax.axvline( x=2004, zorder=1, linewidth=0.5, color='k')
  ax.axvline( x=2012, zorder=1, linewidth=0.5, color='k')

  ax.get_yaxis().set_label_coords(-0.25,0.5)

  ax.set_yticklabels(
    [
      Text(0,0,u''), 
      Text(0,1,u''),
      Text(0,10,u'10 k'),
      Text(0,100,u'100 k'),
      Text(0,1000,u'1 M'),
      Text(0,10000,u'10 M'),
      Text(0,100000,u'100 M'),
      Text(0,1e+06,u'1 B'),
      Text(0,1e+07,u'10 B'), 
      Text(0,0,u''), 
      Text(0,0,u'')
    ]
  )


  brg_plot.plt.tight_layout()
  file_name = 'transistors.pdf'
  brg_plot.plt.savefig( file_name, bbox_inches="tight" )
