#!/usr/bin/env python
#=========================================================================
# plot-voltage-trends
#=========================================================================
#
#  -h --help          Display this message
#
# Author : Shreesha Srinath
# Date   : March 18th, 2018
#
# data collected from Stanford CPUDB

import argparse
import re
import math
import sys

import pandas as pd
pd.set_option('display.width', 1000)

import brg_plot

#-------------------------------------------------------------------------
# main
#-------------------------------------------------------------------------

if __name__ == "__main__":
 
  # create plot options dict
  opts = brg_plot.PlotOptions()
  attribute_dict = \
  {
    'show'            : False,
    'plot_type'       : 'scatter',
    'figsize'         : (4.0, 4.0),
    'rotate_labels'   : False,
    'markersize'      : 10,
    'labels_fontsize' : 1,
    'legend_enabled'  : False,
  }
  for name, value in attribute_dict.iteritems():
    setattr( opts, name, value )

  # get data
  df = pd.read_csv('cpudb-clean.csv')

  ylabel = 'vdd_low'
  yaxis  = df.loc[:,ylabel].tolist()
  ylabel = 'vdd_high'
  yaxis += df.loc[:,ylabel].tolist()
  xaxis  = df.loc[:,'year'].tolist()
  xaxis += df.loc[:,'year'].tolist()
  data   = []
  for x,y in zip( xaxis, yaxis ):
    data.append( [x,y] )

  opts.yrange            = [0,5.1]
  opts.num_cols          = 1
  opts.num_rows          = 1 
  opts.data              = [data]
  opts.index             = 1
  opts.colors            = ['#8aae92'] 
  opts.ylabel            = 'Voltage' 
  opts.grid_enabled      = False
  
  brg_plot.add_plot( opts )

  ax = opts.fig.gca()
  ax.axvline( x=1995, zorder=1, linewidth=0.5, color='k')
  ax.axvline( x=2004, zorder=1, linewidth=0.5, color='k')
  ax.axvline( x=2012, zorder=1, linewidth=0.5, color='k')

  brg_plot.plt.tight_layout()
  file_name = 'voltage.pdf'
  brg_plot.plt.savefig( file_name, bbox_inches="tight" )
